name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          name: just-dates
          directory: coverage
